name: "Publish"

on:
  push:
    tags:
      - "release-*"
jobs:
  publish:
    name: "Publish from master"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v7"
      - name: "Setup Node"
        uses: "actions/setup-node@v7"
        with:
          node-version: 22
      - name: Install
        run: npm ci --ignore-scripts
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc  
          npm publish --access public
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
